version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mi-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: notSecure
    mem_limit: 512m  # Limitar la memoria a 512 MB
    cpus: 1.0   # Asignar la mitad de un núcleo de CPU

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: notSecure
    mem_limit: 512m  # Limitar la memoria a 512 MB
    cpus: 0.5   # Asignar la mitad de un núcleo de CPU

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
    mem_limit: 512m  # Limitar la memoria a 512 MB
    cpus: 0.5   # Asignar la mitad de un núcleo de CPU
