version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mi-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: notSecure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: notSecure
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
